name: Create Bucket

on: [push]

jobs:

    testing-action:

        runs-on: ubuntu-latest
        steps:
            # checkout code
            - uses: actions/checkout@v3

            # # setup node (typescript)
            # - uses: actions/setup-node@v3
            #   with:
            #     node-version: 16

            # - name: "npm install"
            #   run: npm install

            # setup python
            - name: "python"
              uses: actions/setup-python@v4
              with:
                python-version: '3.10' 

            # auth GCP
            - name: "auth GCP"
              uses: "google-github-actions/auth@v1"
              with:
                credentials_json: "${{ secrets.GCP_TOKEN }}"

            # setup gcloud cli
            - name: "setup GCP"
              uses: "google-github-actions/setup-gcloud@v1"

            # pulumi stack initialization
            - name: Initialize Pulumi Stack
              run: pulumi stack init dev
              env:
                PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_TOKEN }}

            # pulumi
            - name: "exec pulumi"
              uses:  pulumi/actions@v3
              with:
                command: preview
                stack-name: dev
              env:
                PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_TOKEN }}